### ISSUE TITLE
Error with sorting and enablePersitence

### ISSUE THREAD

**Issue by jchilde** [syncfusion/ej2-react-grids#2]
I have been using a visual studio 2017 .net core SPA template.

Decided to try your Grid component.  Everything works great with persistence off, but I need that on to deal with a large number of fields.  I am using dynamic properties to populate from SharePoint so I don't know what fields are present at runtime and customers need to be able to select.

Anyway, when I turn on persistence I get the following error on reload (and I have cleared local storage just to make sure that it wasn't corrupted from an earlier build):
 ej2-base.es5.js:158 Uncaught (in promise) TypeError: Cannot add property allowSorting, object is not extensible
    at ej2-base.es5.js:158
    at Array.forEach (<anonymous>)
    at _loop_1 (ej2-base.es5.js:149)
    at extend (ej2-base.es5.js:164)
    at ej2-grids.es5.js:10817
    at Array.forEach (<anonymous>)
    at _loop_2 (ej2-grids.es5.js:10816)
    at ReactPureComponent.Grid.mergePersistGridData (ej2-grids.es5.js:10831)
    at ReactPureComponent.Component.appendTo (ej2-base.es5.js:4966)
    at ReactPureComponent.ComponentBase.componentDidMount (ej2-react-base.es5.js:40)

I am sure that my setup is to blame, but I just can't see where.  Please help confirm that this isn't a bug.  Anything else you might find would be appreciated.

here is my grid component

```
<GridComponent                           
                            dataSource={this.state.matterData}
                            showColumnChooser={true}
                            toolbar={toolbarOptions}
                            enablePersistence={true}
                            allowReordering={true}
                            allowResizing={true}
                            allowTextWrap={true}
                            allowGrouping={true}
                            allowSorting={true}
                        >
                            <ColumnsDirective>{this.state.fieldData}</ColumnsDirective>
                            <Inject services={[Toolbar, ColumnChooser, Group, Reorder, Resize, Sort]} />

                    </GridComponent>
```

this.state.fieldData is a dynamically mapped ColumnDirective populated in componentWillMount.  The GridComponent is not created until the fields are populated.
Here is package.json
{
  "name": "onpointgroupsdashboard",
  "private": true,
  "version": "0.0.0",
  "devDependencies": {
    "@types/history": "4.6.0",
    "@types/react": "15.6.1",
    "@types/react-dom": "15.5.6",
    "@types/react-hot-loader": "3.0.3",
    "@types/react-router": "4.0.12",
    "@types/react-router-dom": "4.0.5",
    "@types/webpack-env": "1.13.0",
    "@types/superagent": "3.5.6",
    "@types/react-select": "1.0.60",
    "aspnet-webpack": "^2.0.1",
    "aspnet-webpack-react": "^3.0.0",
    "awesome-typescript-loader": "^3.2.1",
    "bootstrap": "^3.3.7",
    "css-loader": "^0.28.4",
    "event-source-polyfill": "^0.0.9",
    "extract-text-webpack-plugin": "^2.1.2",
    "file-loader": "^0.11.2",
    "isomorphic-fetch": "^2.2.1",
    "jquery": "^3.2.1",
    "json-loader": "^0.5.4",
    "react": "^15.6.1",
    "react-dom": "^15.6.1",
    "react-hot-loader": "^3.1.3",
    "react-router-dom": "^4.1.1",
    "style-loader": "^0.18.2",
    "url-loader": "^0.5.9",
    "webpack": "^2.5.1",
    "webpack-hot-middleware": "^2.18.2"
  },
  "scripts": {
    "postinstall": "webpack --config webpack.config.vendor.js"
  },
  "dependencies": {
    "@microsoft/microsoft-graph-client": "^1.0.0",
    "@microsoft/microsoft-graph-types": "^1.1.0",
    "@syncfusion/ej2-react-grids": "^15.4.29",
    "aspnet-prerendering": "3.0.1",
    "babel-polyfill": "^6.26.0",
    "intl-messageformat": "^1.3.0",
    "javascript-time-ago": "0.4.10",
    "office-ui-fabric-react": "^5.24.2",
    "react-select": "1.1.0",
    "typescript": "2.6.2"
  }
}

**Comment by Pavithra15** [comment]
Hi @jchilde 

We have checked your query and we could reproduce the reported issue at our end. We have confirmed “Reloading React Grid with persistence throws script error in ASP.NET Core application” as a defect and logged a report for the same. The fix will be available in our February 21, 2018, release.

Regards,
Pavithra S.

**Comment by jchilde** [comment]
any word on this?

**Comment by Pavithra15** [comment]
Hi @jchilde ,

Sorry for the inconvenience caused. We have already fixed the issue 'Reloading React Grid with persistence throws script error in ASP.NET Core application' and the fix for this issue will be available in our Essential Studio Refresh release which will be rolled out on March 6, 2018.

Regards,
Pavithra S.

**Comment by Pavithra15** [comment]
Hi @jchilde ,

We would like to inform that the March 06 , 2018 patch release has been postponed to March 09, 2018 and the fix for the issue will be available in that release. We will update once the release has been rolled out.

Regards,
Pavithra S.

**Comment by jchilde** [comment]
Your fix doesn't apply to react.  Do you have a React fix?

**Comment by Pavithra15** [comment]
Hi @jchilde ,  

We would like to inform that the fix for the issue ‘Reloading React Grid with persistence throws script error in ASP.NET Core application’ will be available in our March 21, 2018, release.    

Regards,  
Pavithra S.
