### ISSUE TITLE
Cannot timely compile sharepoint framework with grid component  

### ISSUE THREAD

**Issue by jchilde** [syncfusion/ej2-react-grids#3]
OOB sharepoint framework webpart takes extra two minutes to compile if grid component added. Seems to hang executing webpack .

Tried shifting to cdn but throwing errors with relative paths.

I am not getting any errors   Where to go from here?

**Comment by Pavithra15** [comment]
Hi @jchilde , 

As per the Microsoft docs recommendation, we are not used Essential JavaScript 2 Grid source in bunding, Please refer below reference link. So that we have used externals option to load EJ2 JavaScript libraries. While creating the sample on this method, we have faced an issue (“Module loading not working properly on EJ2 components with share point”) and logged report for the same, fix will be available on the Essential JavaScript Vol 1 service pack 1 release.  

Bundling: https://docs.microsoft.com/en-us/sharepoint/dev/spfx/toolchain/optimize-builds-for-production#dont-include-third-party-libraries-in-the-bundle  
External libraries: https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/guidance/use-existing-javascript-libraries  

However, we have created a workaround same on the same, you can remove this workaround code snippets after service pack 1 release. Please refer the below code snippets and sample link. 

```
[Essentialjs2WebPart.ts] 
import EJ2Grid from "./grid-html"; 
import { orderData } from "./datasource"; 
import { ej } from "@syncfusion/ej2-grids/dist/global"; 
import { SPComponentLoader } from "@microsoft/sp-loader"; 
…. 
…. 
this.domElement.innerHTML = EJ2Grid.innerHtml; 
    let ej: typeof Essentialjs2WebPart.ej2 = (window as any).ej; // workaround code snippets 
    let grid: any = new ej.grids.Grid({ 
      dataSource: orderData, 
      allowPaging: true, 
      columns: [ 
        { field: "OrderID", headerText: "Order ID", width: 120, textAlign: "Right" }, 
        { field: "CustomerID", headerText: "Customer ID", width: 150 }, 
        { field: "Freight", width: 120, format: "C", textAlign: "Right" }, 
        { field: "ShipName", headerText: "Ship Name", width: 150 }, 
        { field: "ShipCountry", headerText: "Ship Country", width: 150 } 
      ], 
    }); 
…… 
……  
[Config.json] 
"externals": { 
    "@syncfusion/ej2-grids/dist/global": { 
      "path": "https://cdn.syncfusion.com/ej2/dist/ej2.min.js", 
      "globalName": "ej" 
    } 
  }, 
```
Sample: http://www.syncfusion.com/downloads/support/directtrac/general/ze/sharepoint1554776882  

Regards, 
Pavithra S.

**Comment by jchilde** [comment]
Your fix doesn't apply to react. This is the react grid. Do you have a react fix.

**Comment by isuriya-r39** [comment]
Hi jchilde,

While including the external packages in sharepoint we need to refer your external packages in our page. Then only the file will be include in your web part manifest. Grid control was dependable control so its need to load the their dependent packages. For this we have used the  globalDependencies to include grid dependent packages.
For referring the interdependent packages Please refer the below code example:
`"externals": {

    "@syncfusion/ej2-react-grids": {
      "path": "./node_modules/@syncfusion/ej2-react-grids/dist/ej2-react-grids.umd.min.js",
      "globalName": "@syncfusion/ej2-react-grids",
      "globalDependencies": [
        "@syncfusion/ej2-react-base",
        "@syncfusion/ej2-base",
        "@syncfusion/ej2-grids",
        "@syncfusion/ej2-buttons",
        "@syncfusion/ej2-dropdowns",
        "@syncfusion/ej2-inputs",
        "@syncfusion/ej2-lists",
        "@syncfusion/ej2-popups",
        "@syncfusion/ej2-data",
        "@syncfusion/ej2-navigations",
        "@syncfusion/ej2-calendars",
        "@syncfusion/ej2-pdf-export",
        "@syncfusion/ej2-excel-export",
        "@syncfusion/ej2-compression",
        "@syncfusion/ej2-file-utils"
      ]
    },
    "@syncfusion/ej2-react-base": {
      "path": "./node_modules/@syncfusion/ej2-react-base/dist/ej2-react-base.umd.min.js",
      "globalName": "@syncfusion/ej2-react-base"
    },
    "@syncfusion/ej2-base": {
      "path": "./node_modules/@syncfusion/ej2-base/dist/ej2-base.umd.min.js",
      "globalName": "@syncfusion/ej2-base"
    },
    "@syncfusion/ej2-grids": {
      "path": "./node_modules/@syncfusion/ej2-grids/dist/ej2-grids.umd.min.js",
      "globalName": "@syncfusion/ej2-grids"
    },
    "@syncfusion/ej2-buttons": {
      "path": "./node_modules/@syncfusion/ej2-buttons/dist/ej2-buttons.umd.min.js",
      "globalName": "@syncfusion/ej2-buttons"
    },
    "@syncfusion/ej2-dropdowns": {
      "path": "./node_modules/@syncfusion/ej2-dropdowns/dist/ej2-dropdowns.umd.min.js",
      "globalName": "@syncfusion/ej2-dropdowns",
      "globalDependencies": [ "@syncfusion/ej2-data" ]
    },
    "@syncfusion/ej2-inputs": {
      "path": "./node_modules/@syncfusion/ej2-inputs/dist/ej2-inputs.umd.min.js",
      "globalName": "@syncfusion/ej2-inputs",
      "globalDependencies": [ "@syncfusion/ej2-data" ]
    },
    "@syncfusion/ej2-lists": {
      "path": "./node_modules/@syncfusion/ej2-lists/dist/ej2-lists.umd.min.js",
      "globalName": "@syncfusion/ej2-lists",
      "globalDependencies": [  "@syncfusion/ej2-data" ]
    },
    "@syncfusion/ej2-popups": {
      "path": "./node_modules/@syncfusion/ej2-popups/dist/ej2-popups.umd.min.js",
      "globalName": "@syncfusion/ej2-popups",
      "globalDependencies": [ "@syncfusion/ej2-data" ]
    },
    "@syncfusion/ej2-data": {
      "path": "./node_modules/@syncfusion/ej2-data/dist/ej2-data.umd.min.js",
      "globalName": "@syncfusion/ej2-data"
    },
    "@syncfusion/ej2-navigations": {
      "path": "./node_modules/@syncfusion/ej2-navigations/dist/ej2-navigations.umd.min.js",
      "globalName": "@syncfusion/ej2-navigations",
      "globalDependencies": [ "@syncfusion/ej2-data" ]
    },
    "@syncfusion/ej2-calendars": {
      "path": "./node_modules/@syncfusion/ej2-calendars/dist/ej2-calendars.umd.min.js",
      "globalName": "@syncfusion/ej2-calendars"
    },
    "@syncfusion/ej2-pdf-export": {
      "path": "./node_modules/@syncfusion/ej2-pdf-export/dist/ej2-pdf-export.umd.min.js",
      "globalName": "@syncfusion/ej2-pdf-export",
      "globalDependencies": [ "@syncfusion/ej2-compression", "@syncfusion/ej2-file-utils", "@syncfusion/ej2-data" ]
    },
    "@syncfusion/ej2-excel-export": {
      "path": "./node_modules/@syncfusion/ej2-excel-export/dist/ej2-excel-export.umd.min.js",
      "globalName": "@syncfusion/ej2-excel-export",
      "globalDependencies": [ "@syncfusion/ej2-compression", "@syncfusion/ej2-file-utils", "@syncfusion/ej2-data" ]
    },
    "@syncfusion/ej2-compression": {
     "path": "./node_modules/@syncfusion/ej2-compression/dist/ej2-compression.umd.min.js",
      "globalName": "@syncfusion/ej2-compression"
    },
    "@syncfusion/ej2-file-utils": {
      "path": "./node_modules/@syncfusion/ej2-file-utils/dist/ej2-file-utils.umd.min.js",
      "globalName": "@syncfusion/ej2-file-utils"
    }
   
  },
`
Here we have included the all grid dependent packages . Also you need to refer this packages in tsx file. Then only the file will be include in your build .

`import { GridComponent, ColumnsDirective, ColumnDirective } from '@syncfusion/ej2-react-grids';
require('@syncfusion/ej2-react-base');
require('@syncfusion/ej2-base');
require('@syncfusion/ej2-grids')
require("@syncfusion/ej2-buttons");
require("@syncfusion/ej2-dropdowns");
require("@syncfusion/ej2-inputs");
require("@syncfusion/ej2-lists");
require("@syncfusion/ej2-popups");
require("@syncfusion/ej2-data");
require("@syncfusion/ej2-navigations");
require("@syncfusion/ej2-calendars");
require("@syncfusion/ej2-pdf-export");
require("@syncfusion/ej2-excel-export");
require("@syncfusion/ej2-compression");
require( "@syncfusion/ej2-file-utils")
`

Please refer the below sample for your reference:

Sample: http://www.syncfusion.com/downloads/support/directtrac/general/ze/New_Compressed_(zipped)_Folder-316126214.zip


Note : While including the more number of external packages these problem will occurs. For this we need to refer that external file in sample

Link for your reference: https://github.com/SharePoint/sp-dev-docs/issues/1262
