### ISSUE TITLE
Enable Grid Edit on Single Click

### ISSUE THREAD

**Issue by aliklev** [syncfusion/ej2-react-grids#6]
Hi
How can i enable Grid Row Edit on Single Click.
Another issue: Grid in normal Edit  mode/Row: focus  jump to first column/cell and not stay in  double clicked cell.

**Comment by jmfarook** [comment]
We have validated your query and you can achieve your requirement by using  rowSelected event. Please find the below code example and sample for your reference. 
 
`
... 
    } 
rowSelected(args) { 
        this.grid.editModule.startEdit(); 
    } 
 
    render() { 
        return (<div className='control-pane'> 
        <div className='control-section'> 
          <GridComponent dataSource={orderDataSource} ref={g => this.grid = g} rowSelected={this.rowSelected.bind(this)} toolbar={this.toolbarOptions}allowPaging={true} editSettings={this.editSettings} pageSettings={this.pageSettings}> 
            ... 
 
           <Inject services={[Page, Toolbar, Edit]}/> 
          </GridComponent> 
      </div> 
      </div>); 
    } 
} 
 
render(<NormalEdit />, document.getElementById('sample')); 
`
please find the sample:
[sample](https://stackblitz.com/edit/react-hpa3jt?file=index.js )
