### ISSUE TITLE
Cell updating and async cancel event

### ISSUE THREAD

**Issue by aliklev** [syncfusion/ej2-react-grids#8]
How to control the cell updating flow with asynchronous  operation with cancel or commit transaction?

**Comment by jmfarook** [comment]
Hi aliklev,

We suspect that you want to update the cell value dynamically in grid non edit state. We suggest you to use setCellValue method of the Grid to achieve your requirement. Refer the following link to know about this method, 

https://ej2.syncfusion.com/react/documentation/grid/api-gridComponent.html#setcellvalue 

If we misunderstood your query, please share the detailed explanation of your requirement for further assistance. Also which editing you are used in your Grid?.
